version: '2'

services:
  plotter-project-infrastructure:
    image: datumgeek/plotter-project-infrastructure
    ports:
      - "32776:80"
  mongo:
    image: mongo
#    uncomment the lines if you want to connect robo mongo to the mongo instance
#    ports:
#      - "27017:27017"
  sqlnorth:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yukon900
    image: datumgeek/sqlnorth
    labels:
      com.microsoft.visualstudio.targetoperatingsystem: linux
#    uncomment the lines if you want to connect sql server management studio to the sql server instance
#    ports:
#      - "1435:1433"