version: '2'

services:
  plotter-project-infrastructure:
    image: plotter-project-infrastructure
    build:
      context: ./plotter-project-infrastructure
      dockerfile: Dockerfile

  mongo:
    image: mongo
    ports:
      - "27017:27017"