version: '2'

services:
  plotter-project-infrastructure:
    image: plotter-project-infrastructure
    build:
      context: ./plotter-project-infrastructure
      dockerfile: Dockerfile
    ports:
      - "32776:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  corstesterwebapp:
    image: corstesterwebapp
    build:
      context: ./CorsTesterWebApp
      dockerfile: Dockerfile
    ports:
      - "32777:80"
  sqlnorth:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Yukon900
    image: sqlnorth
    labels:
      com.microsoft.visualstudio.targetoperatingsystem: linux
    build:
      context: ./plotter-project-infrastructure/NorthwndDockerContainer
      dockerfile: Dockerfile
    ports:
      - "1435:1433"
